### ISSUE TITLE
Remove all href-tags from the HTML anchors

### ISSUE THREAD

**Issue by leicht-io** [ixtendo/Polyglot-Language-Switcher-2#3]
Please remove all the href="#" from the anchors.
It interferes with the states, since the url will get changes on click and an update will redirect.

**Comment by poqdavid** [comment]
Hi
i currently fixed few problems you can check them here https://github.com/poqdavid/Polyglot-Language-Switcher-2/
and also i did made a pull request

**Comment by mbriskar** [comment]
I experienced the issue and needed to remove # from href. I have sent PR for the angular.js part. 
https://github.com/ixtendo/Polyglot-Language-Switcher-2/pull/6

**Comment by ixtendio** [comment]
Hi,

I merged all the pull requests into master. Thank you poqdavid and mbriskar for your contribution.
